name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04  # Explicit Ubuntu version

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4  # Updated to v4

      - name: Setup Node
        uses: actions/setup-node@v4  # Updated to v4
        with:
          node-version: 18  # Explicit Node.js version

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: |
          npm run build
          # Create 404.html for client-side routing
          cp dist/index.html dist/404.html

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-22.04  # Explicit Ubuntu version
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4  # Updated to v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # Forcefully update deployment history
          force_orphan: true