name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write  

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: |
          npm run build
          # Add CNAME if using custom domain
          # echo "yourdomain.com" > dist/CNAME
          
          # Client-side routing fix
          cp dist/index.html dist/404.html

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: dist/

  deploy:
    name: Deploy to GH Pages
    needs: build
    runs-on: ubuntu-22.04
    environment: github-pages

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-build
          path: dist/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # Forcefully update deployment history
          force_orphan: true
          enable_jekyll: false 
          keep_files: false